import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Libre_Caslon_Text } from "next/font/google";
import "./globals.css";
import Providers from "@/components/layout/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const libreCaslonText = Libre_Caslon_Text({
  variable: "--font-libre-caslon-text",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * [Server Component] 루트 레이아웃
 *
 * 역할:
 *   App Router의 최상위 레이아웃이다. `(shop)`, `(auth)`, `(protected)`, `admin` 등
 *   모든 라우트 그룹의 페이지가 이 레이아웃을 공통으로 거쳐간다 — 즉 앱의 모든 화면에
 *   예외 없이 적용되는 단 하나의 공통 껍데기다.
 *
 * children이란 무엇인가 (비유: 상자):
 *   `children`은 Next.js가 현재 접속한 URL에 맞게 렌더링한 페이지 트리 전체를
 *   하나로 담아 넘겨주는 "상자"다. 홈이면 `(shop)/page.tsx`의 결과물, 상품 상세면
 *   `products/[id]/page.tsx`의 결과물이 이 상자 안에 들어있다.
 *   RootLayout은 상자 안에 뭐가 들어있는지 들여다보지 않는다 — 그냥 통째로 다룬다.
 *
 * Providers를 호출하면서 children을 넘기는 것의 의미:
 *   `<Providers>{children}</Providers>`는 "내가 받은 상자를 열어보지 않고
 *   그대로 Providers에게 건네준다"는 뜻이다. 각 자식 컴포넌트에 children을
 *   개별적으로 나눠주는 게 아니라, 페이지 트리 전체를 한 번에 통째로 넘기는 것뿐이다.
 *
 * Providers로 감싸면 생기는 일 (비유: 포장지):
 *   Providers 내부의 `QueryClientProvider`는 상자(children) 바깥을 감싸는 포장지와
 *   같다. 상자 안의 컴포넌트들이 props로 직접 뭔가를 받는 게 아니라, 나중에
 *   `useQuery`/`useInfiniteQuery` 같은 훅을 호출하면 "자신을 감싸고 있는 포장지에
 *   적힌 queryClient를 찾아 쓰는" 방식(React Context)으로 동작한다.
 *   이 포장지가 없으면 ProductGrid 같은 컴포넌트가 useInfiniteQuery를 호출할 때
 *   "QueryClient를 찾을 수 없다"는 에러가 난다.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${libreCaslonText.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
