// This file was generated by Prisma, and assumes you have installed the following:
// dotenv/config 를 사용하기 위해서는 먼저 npm install --save-dev dotenv 를 설치해야 합니다.
import "dotenv/config"; // .env 파일을 읽어서 process.env에 환경 변수를 설정합니다.
import { defineConfig } from "prisma/config"; // Prisma 설정을 정의하는 함수를 가져옵니다.

// Prisma 설정을 정의합니다. defineConfig 함수는 Prisma의 설정을 구성하는 데 사용됩니다.
export default defineConfig({
  schema: "prisma/schema.prisma", // Prisma 스키마 파일의 경로를 지정합니다.
  migrations: {
    path: "prisma/migrations", // 마이그레이션 파일의 경로를 지정합니다. packages/database/prisma/migrations 폴더에 마이그레이션 파일이 생성됩니다.
    seed: "tsx prisma/seed.ts", // npx prisma db seed 명령어를 실행할 때 seed 스크립트를 지정합니다. 여기서는 tsx를 사용하여 TypeScript로 작성된 seed.ts 파일을 실행합니다.
  },
  datasource: {
    url: process.env["DATABASE_URL"], // 환경 변수에서 데이터베이스 URL이 있으면 가져와서 prisma datasource URL로 사용합니다.
  },
});
